// sidebarsApi.js
// module.exports = {
//     apiSidebar: [
//       {
//         type: 'category',
//         label: 'API Reference',
//         collapsible: false,
//         items: [
//           'createComponent',
//           'useRefraction',
//           'useEffect',
//           'useOptic',
//           'useFlash',
//           {
//             type: 'category',
//             label: 'Animation API',
//             collapsible: true,
//             collapsed: true,
//             items: [
//               'animationApi/test', 
//             ],
//           },
//         ],
//       },
//     ],
//   };

  module.exports = {
    apiSidebar: [{ type: 'autogenerated', dirName: '.' }],
  };
  