// module.exports = {
//     tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
//   };

module.exports = {
    tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  };

//   module.exports = {
//     tutorialSidebar: [
//       {
//         type: 'category',
//         label: 'Tutorial',
//         collapsible: false,
//         items: [
//           'counterApp',
//         ],
//       },
//     ],
//   };